
try:
    print("try")
except Exception as e:
    print("except Exception")
finally:
    print("finally")
